import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const body = await req.json();

  const worksheet = `
THE ADITYA BIRLA PUBLIC SCHOOL, RENUKOOT

Class: ${body.className}
Subject: ${body.subject}
Chapter: ${body.chapter}

======================================

Section A (MCQs)

Q1.
Q2.
Q3.
Q4.
Q5.

======================================

Section B (Short Answer)

Q6.
Q7.
Q8.

======================================

Section C (Long Answer)

Q9.
Q10.

======================================

Answer Key

(To be generated by AI)
`;

  return NextResponse.json({
    success: true,
    worksheet,
  });
}